fpo-web/src/assets/survey-primary.json
PFCF24: Label change completed
PFCF25: Reword ex partner question
PFCF26: Added new questionnaire
PFCF27: Added name description
PFCF28: Deleted existing file name
=> PO survey changes

fpo-web/src/assets/survey-primary.json
PFCF-29: Added new interaction for existing order
PFCF-30: Added new interaction for written agreements
PFCF-31: Deleted Step
=> PO Survey Changes Part-2

fpo-web/src/app/survey/primary.component.ts, fpo-web/src/assets/survey-primary.json, fpo-web/src/assets/survey-qualify.json
PFCF-17: Updated changes
PFCF-25: Changed the wording
PFCF-26: Updated the flow
=> Jira Rework

fpo-web/src/assets/survey-primary.json, fpo-web/src/assets/survey-qualify.json
=> PFCF-69: Deleted Pre-qual ques

fpo-web/src/assets/survey-primary.json
Updated as per Erin's comments
=> PFCF-30: Written Agreement

fpo-web/src/assets/survey-information.json, fpo-web/src/assets/survey-parenting.json
General Information includes:
-Your Information
-Other Party Information
=> Survey description for general(common) information, Survey description for Parenting arrangements and child support

fpo-web/openshift/templates/nginx-runtime/s2i/bin/run
See https://github.com/bcgov/TheOrgBook/pull/867
=> Fixes string replacement for api service names with multiple slashes.

fpo-pdf/templates/application-for-case-management-order-without-notice-or-appearance.html, fpo-pdf/templates/application-for-case-management-order.html, fpo-pdf/templates/application-for-enforcement.html
=> More forms

fpo-web/openshift/templates/nginx-runtime/Dockerfile
=> Fix file and folder permissions on nginx-runtime

fpo-web/src/app/survey/survey.component.ts, fpo-web/src/assets/survey-parenting.json
JSON: Added Fact sheet
Survey Component: Wired data from dynamic panel
=> PFCF-55: Added Fact sheet & Wiring dynamic data

fpo-web/package.json, fpo-web/src/app/survey/survey.component.ts, fpo-web/src/assets/survey-parenting.json, fpo-web/src/index.html
Created a dynamic panel based on the user selection
=> PFCF-54: Data setup for dynamic panel

docker/docker-compose.yml, fpo-api/README.md, fpo-api/fpo_api/views.py
This is temporary for development only
=> Opening port 8000 on API container

.gitignore, fpo-api/README.md, fpo-api/fpo_api/urls.py, fpo-api/fpo_api/views.py, fpo-api/templates/family-law-matter-claim.html, fpo-web/src/app/survey/survey.component.ts
There is one end point /form and all templates will be specified by URL argument name=name-of-template
=> Final name and format of end point

fpo-web/src/assets/survey-information.json
Survey json for application information
=> Added single page applicant information survey

fpo-web/src/assets/PO Form/aboutPO.json, fpo-web/src/assets/PO Form/background.json, fpo-web/src/assets/PO Form/protectionFromWhom.json, fpo-web/src/assets/PO Form/safteyNeeds.json, fpo-web/src/assets/PO Form/urgency.json, fpo-web/src/assets/PO Form/yourStory.json, fpo-web/src/assets/survey-childInfo.json, fpo-web/src/assets/survey-opInfo.json, fpo-web/src/components/status/ApplicationStatus.vue, fpo-web/src/routes.js
-Protection order
-Other Party
-Children info
=> Smaller surveys

fpo-api/templates/family-law-matter-claim.html
Finished these two schedules until data gets pulled from Vuex.
=> Schedule 1 & 2

fpo-web/src/assets/service-locator.json, fpo-web/src/components/steps/get-started/GettingStarted.vue, fpo-web/src/components/steps/submit/SubmitApplication.vue, fpo-web/src/components/views/LandingPage.vue, fpo-web/src/components/views/ServiceLocator.vue
Changes include:  
- PFCF-186: Changed the background for the landing page 
- PFCF-184:  Changed the styling of text on the getting started page 
- PFCF-185:  Changed the yes-no button styles on the service-locator page.
=> PFCF-186: various requested changes to the UI

fpo-web/src/assets/service-locator.json, fpo-web/src/components/steps/get-started/GettingStarted.vue, fpo-web/src/components/views/LandingPage.vue, fpo-web/src/components/views/ServiceLocator.vue
Changes include:  
- PFCF-186: Changed the background for the landing page  
- PFCF-184:  Changed the styling of text on the getting started page  
- PFCF-185:  Changed the yes-no button styles on the service-locator page.
=> PFCF-186: various requested UI changes

fpo-web/openshift/templates/vue-on-nginx/vue-on-nginx-deploy.yaml
=> Update route configuration.

api/README.md
=> Minor change to test build trigger.

api/api/auth.py, api/api/views/UserView.py, web/src/components/utils/utils.ts
I sent an email about the SSO changes for this.
=> Use display_name for username display.

jenkins/config.groovy
=> Include all of the web components in the web-pipeline

web/src/components/NavigationTopbar.vue, web/src/components/status/ApplicationStatus.vue, web/src/components/steps/PageBase.vue, web/src/components/steps/get-started/GettingStarted.vue, web/src/components/steps/get-started/Questionnaire.vue, web/src/components/steps/protectionOrder/Background.vue, web/src/components/steps/protectionOrder/ProtectionFromWhom.vue, web/src/components/steps/protectionOrder/safetyNeeds/RemovePerson.vue, web/src/components/steps/submit/FilingOptions.vue, web/src/components/steps/submit/ReviewAndPrint.vue, web/src/components/steps/submit/ReviewAndSave.vue, web/src/components/steps/submit/SubmitApplication.vue, web/src/components/views/ServiceLocator.vue, web/src/store/modules/application/mutations.ts
Refer to https://github.com/bcgov/family-law-act-app/pull/155 for details
=> Return to top of page when navigating through steps/pages

web/src/assets/POForm/background.json, web/src/assets/POForm/protectionFromWhom.json, web/src/assets/survey-opInfo.json, web/src/components/steps/common-information/otherPartyComponent/OtherParty.vue, web/src/components/steps/get-started/Questionnaire.vue
refer to https://github.com/bcgov/family-law-act-app/pull/157 for details
=> Changes to the Other-Party pathway

web/src/components/home/ServiceLocator.vue
refer to https://github.com/bcgov/family-law-act-app/pull/164 for details.
=> Add disclaimer pop-up window

web/src/components/home/LandingPage.vue
Refer to https://github.com/bcgov/family-law-act-app/pull/167 for details
=> Add instructions on BCeID registration requirement to the landing page

web/public/index.html
Add in Matamoto script into base index.html
=> Add in Matamoto script into base index.html

openshift/manage
- Add support for building and deploying from a local working copy of code.  Allowing any version of the application to be built and deployed for preview at any time.
=> Update manage script

openshift/templates/db/db-build.param
=> Switch db image over to use artifactory

web/src/components/home/ServiceLocator.vue, web/src/components/status/ApplicationStatus.vue, web/src/components/steps/common-information/Information.vue, web/src/components/steps/common-information/otherPartyComponent/OtherPartyCommon.vue, web/src/components/steps/familyLawMatter/contactWithChild/forms/about-contact-with-child-order.json, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Form3.vue, web/src/components/steps/protectionOrder/About.vue, web/src/components/steps/protectionOrder/ProtectionFromWhom.vue, web/src/components/steps/protectionOrder/reviewPo/pdf/FormK.vue, web/src/components/steps/submit/ResultPage.vue, web/src/components/steps/submit/components/FormList.vue, web/src/components/utils/utils.ts
Changes include: 
- PFCF-58: added functionality to support the new 'contact with child' pathway  
- PFCF-59: added functionality to support the existing 'contact with child' pathway 
- Integration with latest eFiling and pdf generation API changes
- Enabling efiling for PO applications 
- Enabling pdf generation for Protection-Order and Family-Law-Matter forms
=> Adding functionality to support PO efiling and Family-law-matter's contact-with-child pathways

api/api/efiling/efiling_resources.py, web/src/components/status/ApplicationStatus.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule10.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule3.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule4.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule7.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule9.vue, web/src/components/steps/submit/FilingOptions.vue, web/src/components/steps/submit/NextSteps.vue, web/src/components/steps/submit/ReviewAndPrint.vue, web/src/components/steps/submit/ReviewAndSave.vue, web/src/components/steps/submit/ReviewAndSubmit.vue, web/src/components/steps/submit/components/RequiredDocument.vue, web/src/components/steps/submit/forms/filingOptions.json, web/src/filters/index.ts
refer to https://github.com/bcgov/family-law-act-app/pull/220 for details
=> Review and File - updates and revisions.  Changes based on feedback.

api/api/fixtures/api_location.json
=> Email address updates

web/src/components/status/ApplicationStatus.vue, web/src/components/steps/familyLawMatter/childSupport/AboutChildSupportOrder.vue, web/src/components/steps/familyLawMatter/parentingArrangements/ParentalResponsibilities.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule1.vue, web/src/components/steps/protectionOrder/reviewPo/pdf/FormK.vue, web/src/components/steps/submit/forms/filingOptions.json, web/src/components/survey/survey-glossary.ts, web/src/styles/_survey.scss, web/src/styles/index.scss
Changes include:
- Resolve issue with populating schedule-1 
- Change behaviour of popup glossary definitions
=> Applying changes based on feedback

web/src/components/home/LandingPage.vue, web/src/components/steps/familyLawMatter/childSupport/forms/child-support-income-earning.json, web/src/components/steps/familyLawMatter/childSupport/forms/child-support.json, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule3.vue
Please deploy in test to keep the dev environment as a preview for additional pathways
=> PFCF-290: updates to the child-support pathway based on feedback

web/src/components/steps/caseMgmt/ContactInformationOtherParty.vue, web/src/components/steps/caseMgmt/childInfo/CmChildrenInfo.vue, web/src/components/steps/caseMgmt/forms/cm-notice.json, web/src/components/steps/caseMgmt/forms/contact-information-other-party.json, web/src/components/steps/caseMgmt/orderTypesCM.ts, web/src/components/steps/caseMgmt/reviewCM/ReviewYourAnswersCM.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Form10Layout.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/CommonSection.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/Schedule5.vue, web/src/components/steps/childReloc/childInfo/RelocChildrenInfo.vue, web/src/components/steps/childReloc/reviewRELOC/pdf/Form16Layout.vue, web/src/components/steps/common-information/otherPartyComponent/OtherPartyCommon.vue, web/src/components/steps/common-information/otherPartyComponent/OtherPartyCommonSurvey.vue, web/src/components/steps/common-information/otherPartyComponent/forms/survey-opInfo.json, web/src/components/steps/familyLawMatter/childInfo/ChildrenInfo.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Form1Layout.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/CommonSection.vue, web/src/components/steps/priorityParenting/childInfo/PpmChildrenInfo.vue, web/src/components/steps/priorityParenting/reviewPPM/pdf/Form15Layout.vue, web/src/components/steps/protectionOrder/otherPartyComponent/OtherParty.vue, web/src/components/steps/protectionOrder/reviewPo/pdf/FormK.vue, web/src/components/survey/components/AddressInfo.vue, web/src/components/survey/components/CaProvinceList.json, web/src/filters/index.ts, web/src/types/Application/CaseManagement/PDF/index.ts, web/src/types/Application/CommonInformation/index.ts
Note: please don't merge this into master.
We'll need it to be in preview mode on dev, for review and feedback.
=> PFCF-289: adding functionality to support schedule 5 and adding hover text over edit/delete buttons

web/src/components/steps/caseMgmt/forms/contact-information-other-party.json, web/src/components/steps/caseMgmt/forms/recognizing-an-order-from-outside-bc.json, web/src/types/Application/CaseManagement/index.ts, web/src/types/Application/index.ts
Note: please don't merge this into master.
We'll need it to be in preview mode on dev, for review and feedback.
=> PFCF-289: applying changes based on feedback

web/vue.config.js
turn transpileOnly -> true, better performance.
=> Production Build Performance - Update vue.config.js

api/core/database.py
Use postgresql by default. This should fix building of static files.
=> Use postgresql by default. This should fix building of static files.

api/api/efiling/__init__.py, api/api/efiling/efiling_resources.py, api/api/efiling/efiling_submission.py, api/api/efiling/exceptions.py, api/api/settings.py
=> PFCF-312 - Sonar cloud fixes

web/src/components/steps/caseMgmt/CmQuestionnaire.vue, web/src/components/steps/caseMgmt/orderTypesCM.ts, web/src/filters/index.ts
Reverts bcgov/family-law-act-app#556
=> Revert "PFCF-439: applying changes based on further requirements"

web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/CommonSection.vue
Reverts bcgov/family-law-act-app#552
=> Revert "PFCF-439: updates based on Form 11 changes"

web/src/components/steps/caseMgmt/forms/application-under-foaeaa.json
Reverts bcgov/family-law-act-app#551
=> Revert "PFCF-439: applying changes based on feedback"

api/api/stats/statistics.py, api/api/urls.py, api/api/views/statistics_view.py, web/src/components/NavigationTopbar.vue, web/src/components/statistics/Statistics.vue, web/src/prototypes/UpdateGotoStep.ts
Reverts bcgov/family-law-act-app#597
=> Revert "initial changes to resolve report issue"

web/README.md, web/package-lock.json, web/package.json, web/src/components/steps/addressChange/AddressChangeStep.vue, web/src/components/steps/addressChange/OtherParty.vue, web/src/components/steps/addressChange/forms/other-party.json, web/src/components/steps/addressChange/reviewNCD/pdf/Form46Layout.vue, web/src/components/utils/PopulateForms/components/UnderlineForm.vue, web/src/components/utils/ReviewYourAnswers/ReviewYourAnswersPage.vue, web/src/store/modules/application.ts, web/src/styles/_pdf.scss, web/src/types/Application/StepsAndPages/index.ts
PFCF-461: Update notice of address change form
=> PFCF-461: Update notice of address change form

web/src/components/steps/addressChange/reviewNCD/pdf/Form46Layout.vue, web/src/components/utils/PopulateForms/components/UnderlineForm.vue
=> PFCF-461: Fix styles

web/src/components/steps/agreementEnfrc/reviewAE/pdf/Form29Layout.vue
Form29 Layout changes
Open Issue:
- Line break missing from facts & details of order.
=> Form 29 layout changes.

web/src/components/steps/writtenResponse/forms/agree-disagree.json, web/src/components/steps/writtenResponse/forms/wr-replying-to-application.json, web/src/components/steps/writtenResponse/reviewWR/pdf/Form19Layout.vue, web/src/filters/index.ts, web/src/types/Application/WrittenResponse/PDF/index.ts, web/src/types/Application/WrittenResponse/index.ts
=> Form 19 changes.

web/src/components/steps/childReloc/reviewRELOC/pdf/Form16Layout.vue
Updated Form 16 to the new Forms
=> PFCF-488 : Form 16- Application for Order Prohibiting the Relocation of a child 

web/src/components/steps/affidavitPersonalServicePO/reviewAPSP/pdf/Form49Layout.vue, web/src/components/steps/affidavitPersonalServicePO/reviewAPSP/pdf/Form51Layout.vue, web/src/components/utils/PopulateForms/components/GreyBoxForm.vue
PFCF-471:  form 49 and form 51
=> PFCF-471:  form 49 and form 51

web/src/components/steps/agreementEnfrc/reviewAE/pdf/Form29.vue, web/src/components/steps/agreementEnfrc/reviewAE/pdf/Form29Layout.vue, web/src/filters/index.ts
This PR includes,
1. The label "For Registry use only" is missing under the Document Number section.
Sumathi: Changes completed
2. The size of the info and guidebook icons appears larger than specified.
Sumathi: Included the right icons for paperclip and guidebook.
3. Inconsistent spacing in bullet points.
Sumathi: Changes completed
4. Missing colon (:) in Part 1, Section 1.
Sumathi: Changes completed
5. Alignment issue with checkboxes in Section 3 of Part 1.
Sumathi: Changes completed
6. Discrepancy in the text fond "Interjurisdictional Support Orders Act."
Sumathi: Changes completed
7. Extra Brackets() around the date and time in Part 3.
Sumathi: Changes completed
8.Missing Attachment icon and Book icon 
Sumathi: Changes completed
9. Missing bold formatting for "Do not attend the …
=> PFCF-485 - Form 29 Fixes.

web/src/components/steps/priorityParenting/reviewPPM/pdf/Form15Layout.vue, web/src/components/steps/priorityParenting/reviewPPM/pdf/Schedule2.vue
style: adjust look and feel of form 15
style: adjust look and feel of schedule 2
https://github.com/user-attachments/assets/67813882-a4c9-47db-a0fd-8f61b9477da7
=> Form 15/Schedule 2

web/src/components/steps/agreementEnfrc/reviewAE/pdf/Form29Layout.vue, web/src/filters/index.ts
Fixes to support invalid input for date formatter function.
=> Date formatting fix for Form 29 to return default value.

web/src/components/steps/caseMgmt/forms/attendance-using-electronic-communication.json, web/src/components/steps/caseMgmt/reviewCM/pdf/Form10.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Form10Layout.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Form11.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/CommonSection.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/Schedule1.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/Schedule3.vue
Layout changes for Form 11 + Schedule 1 & 3.
=> Form 11, Schedule 1 & 3.

web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/Schedule4.vue, web/src/components/steps/caseMgmt/reviewCM/pdf/Schedules/Schedule5.vue
Added schedules 4 and 5 for Form 11
=> PFCF-492: Form 11 schedule 4 and 5

web/src/components/steps/childReloc/reviewRELOC/pdf/Form16.vue, web/src/components/steps/childReloc/reviewRELOC/pdf/Form16Layout.vue, web/src/components/utils/PopulateForms/components/CheckBox.vue, web/src/components/utils/PopulateForms/components/GreyBoxForm.vue
Bug Fixes for Form 16
- Added missing footer application name
- Fixed the background color for check boxes
- Fixed the greybox margin top styles
- Fixed the textbox background colors
=> Forms/pfcf 488 form 16 child relocate act Bug fixes

web/src/components/steps/priorityParenting/reviewPPM/pdf/Form15Layout.vue, web/src/components/steps/priorityParenting/reviewPPM/pdf/Schedule2.vue
=> Form 15 Issue Fixes

web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Schedules/Schedule4.vue
style: adjust schedule 4 to have new styling and information
=> PFCF 494 - Form 6 Schedule 4

web/src/components/steps/common-information/forms/filing-location.json, web/src/components/steps/priorityParenting/reviewPPM/pdf/Form15Layout.vue
refactor: the available options for filing location reasons
=> PFCF 486 - Form 15 Filing Location Reasons

web/src/components/steps/common-information/forms/filing-location.json, web/src/components/steps/priorityParenting/reviewPPM/pdf/Form15Layout.vue
Undoing https://github.com/bcgov/family-law-act-app/pull/653/ due to issues identified by @shruthi-rapala 
Will have to come up with another solution over the weekend
=> Undo Location Changes

web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Schedules/Schedule1.vue
PFCF # 493 Form 6 Replying to an application about Family Law Matter 
- Finished Schedule 1
=> PFCF # 493 Form 6 Replying to an application about Family Law Matter 

web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Schedules/Schedule4.vue
Because I match the numbers, not the titles, I changed schedule 4 when I should have changed Schedule 7
Reverting for now and will do a proper fix during my full day of work tomorrow.
=> Revert "PFCF 494 - Form 6 Schedule 4"

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule5.vue
style: fix style issues in schedule 5
=> PFCF-491 - Form 3 - Schedule 5 fixes

web/src/components/FlappSurveys.vue, web/src/components/status/MigrateStore.ts, web/src/components/steps/familyLawManual/FamilyLawManual.vue, web/src/components/steps/familyLawManual/FamilyLawManualStep.vue, web/src/components/steps/get-started/ReplyToApplication.vue, web/src/components/steps/replyFamilyLawMatter/RflmQuestionnaire.vue, web/src/components/steps/replyFamilyLawMatter/parentingArrangements/forms/reply-new-parental-responsibilities.json, web/src/components/steps/replyFamilyLawMatter/parentingArrangements/forms/reply-new-parenting-time.json, web/src/filters/applicationTypes.ts, web/src/store/modules/application.ts, web/src/types/Application/StepsAndPages/index.ts, web/src/types/Application/index.ts
This PR is for manual filing of Form 6.
=> Form 6 manual filing options.

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule5.vue
style: update main note area font size from 9 to 10 to be aligned with other schedules
=> PFCF-491 - Schedule 5 Note Font Size

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule5.vue
refactor: add in missing side note boxes that werent caught by QA
=> PFCF 491 - Form 3 Schedule 5 Missing Note Boxes

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule1.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule11.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule12.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule2.vue
Fixed background color on Schedule 1, 2, 11, 12
=> Pfcf 491 form 3 bugs

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule5.vue
style: adjust bold and shading based on QA's findings
=> PFCF 491 - Form 3 Schedule 5 Styling Fixes

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule2.vue
=> PFCF- 491 form 3 bugs - Schedule 2

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/Schedule4.vue
style: shading
style: page breaks
style: missing text
=> PFCF 491 - Schedule 4

web/src/components/steps/affidavitPersonalServicePO/reviewAPSP/pdf/Form49.vue, web/src/components/steps/affidavitPersonalServicePO/reviewAPSP/pdf/Form49Layout.vue, web/src/components/steps/affidavitPersonalServicePO/reviewAPSP/pdf/Form51.vue, web/src/components/steps/affidavitPersonalServicePO/reviewAPSP/pdf/Form51Layout.vue
PFCF # 471 Fixed bugs on Form 49 and 51
=> PFCF # 471 : Form 49 and 51

web/src/components/steps/addressChange/reviewNCD/pdf/Form46.vue
PFCF-461: Fix footer in Notice of address change
=> PFCF-461: Fix footer in Notice of address change

web/src/components/steps/affidavit/reviewAFF/pdf/Form45Layout.vue, web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form48.vue, web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form48Layout.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/CommonSection.vue, web/src/components/utils/PopulateForms/components/FormFooterSignature.vue, web/src/components/utils/PopulateForms/components/FormHeader.vue
- fix footer signature width
- fix common section in form 3
- fix hint fontsize as binding property
=> PFCF-464: Form 48 Affidavit of Personal Service

web/src/components/steps/guardianshipAffidavit/reviewGA/pdf/Form5Layout.vue, web/src/components/steps/otherFamilyForms/OtherForms.vue
refactor: add in missing other party last name fields
=> PCFC 481 - Form 5 - Other Party LastNames field

web/src/components/steps/childReloc/reviewRELOC/pdf/Form16.vue, web/src/components/steps/childReloc/reviewRELOC/pdf/Form16Layout.vue
- Fixed header and footer styling issues
- Fixed the hint colors on all the fields
- Fixed white spacing issues
- Fixed the italicized text color issue
- Fixed Formatting issues on Part 4 an 
- Fixed the overlapping text for question 8 part 5
- Fixed the height for the Part 6
- Fixed additional styles on the form 16
=> PFCF#488 Form 16 Application for order prohibiting the relocation of a child

web/src/components/steps/guardianshipAffidavit/reviewGA/pdf/Form5.vue, web/src/components/steps/guardianshipAffidavit/reviewGA/pdf/Form5Layout.vue, web/src/components/utils/PopulateForms/components/FormHeader.vue, web/src/components/utils/PopulateForms/components/NoteBox.vue
style: style changes to address styling issues
refactor: notebox text color adjustable
refactor: formheader rule font size adjustable
=> Form5 Layout Fixes

web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form48.vue, web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form48Layout.vue, web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form51.vue, web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form51Layout.vue
- Convert form 51 to new format
=> PFCF-464: Form 48 Affidavit of personal service fixes

web/src/components/steps/priorityParenting/reviewPPM/pdf/Form15Layout.vue
style: add missing italics
style: table formatting
=> Form15 further fixes

web/src/components/steps/trialReadinessStatement/forms/issues-for-trial.json, web/src/components/steps/trialReadinessStatement/forms/witnesses.json, web/src/components/steps/trialReadinessStatement/reviewTRIS/pdf/Form22.vue, web/src/components/steps/trialReadinessStatement/reviewTRIS/pdf/Form22Layout.vue, web/src/types/Application/TrialReadinessStatement/index.ts
style: adjust layout styling for form 22
=> Form22 Layout Changes

web/src/components/steps/trialReadinessStatement/reviewTRIS/pdf/Form22Layout.vue
=> Form 22 Fixes

web/src/components/steps/trialReadinessStatement/reviewTRIS/pdf/Form22Layout.vue
fix: fix wrong text spacing and background color
=> Form 22 Fix Wrong Spacing/Color

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Form1.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Form1Layout.vue
=> Further Form 1 Fixes

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Form1.vue, web/src/components/steps/familyLawMatter/reviewFLM/pdf/Form1Layout.vue
fix: final form 1 styling fixes
=> Form 1 Final Styling Fixes

web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Schedules/Schedule11.vue
- Worked on Schedule 7 on Form 6
=> PFCF-493  Form 6- Reply to the application about the Family Law

web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Form6.vue, web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Schedules/Schedule10.1.vue
Schedules 10.1 and 10.2 have been merged down into one, Schedule 6 using schedule 10.1's file
style: adjust schedules layout
refactor: trigger new schedule from 10.1 and 10.2 workflows
=> Form 6 Schedule 6

web/src/components/steps/affidavit/reviewAFF/pdf/Form45Layout.vue, web/src/components/steps/affidavit/reviewAFF/pdf/Form51Layout.vue, web/src/components/steps/affidavitPersonalService/reviewAPS/pdf/Form51Layout.vue
PFCF-464: Form 48 - Affidavit of Personal Service and EFS fixes, Form 51 fixes
PFCF-466: Form 45 - Affidavit - General fixes, Form 51 fixes
=> PFCF-464, PFCF-466 Fixes 

web/src/components/steps/familyLawMatter/reviewFLM/pdf/Schedules/CommonSection.vue, web/src/components/steps/writtenResponse/reviewWR/pdf/Form19Layout.vue
PFCF-502: Fix Form 3 main section not showing up
PFCF-503: Fix Form19 blank page issue
=> PFCF-502, PFCF-503: Fix Form 3, Form 19 null or undefined issue 

web/src/components/steps/affidavit/ElectronicFilingStatementLayout.vue, web/src/components/steps/guardianshipAffidavit/reviewGA/pdf/Form51Layout.vue
I noticed a good chunk of affidavits form 51's in the system are identical (some are different) so I create a component for the similar form 51's to use
feat: add generic form 51
fix: styling bugs in form 5s form 51
=> Form 5 Form 51

web/src/components/steps/replyFamilyLawMatter/reviewRFLM/pdf/Schedules/Schedule7.vue
style: form 6 schedule 4 styling changes
=> PFCF-493 - Form 6 Schedule 4

web/src/filters/locationRegistries.ts
- Abbosford Law Courts, 
- Chilliwack Law Courts, 
- New Westminster Law Courts
=> PFCF-511: Update early resolutions registries 

web/src/components/steps/certificateOfService/reviewCSV/pdf/Form51Layout.vue, web/src/components/steps/certificateOfService/reviewCSV/pdf/Form7Layout.vue, web/src/components/utils/PopulateForms/components/FormHeader.vue
=> PFCF-484: Fix background for text boxes

web/src/components/steps/requestScheduling/reviewRQS/pdf/Form39Layout.vue, web/src/components/utils/PopulateForms/components/FormPart.vue
=> PFCF-477: Form 39  update important information page

web/src/components/steps/protectionOrder/reviewPo/pdf/Schedules/CommonSection.vue, web/src/components/steps/protectionOrder/reviewPo/pdf/Schedules/Schedule1.vue, web/src/components/steps/protectionOrder/reviewPo/pdf/Schedules/Schedule2.vue, web/src/components/steps/protectionOrder/reviewPo/pdf/Schedules/Schedule3.vue
Most of it is formatting to figure out the html tags and layout issue.
=> PFCF-518: Fix showing information in one page and schedules in new page

web/src/components/steps/caseMgmt/reviewCM/pdf/Form10Layout.vue, web/src/components/steps/common-information/FilingLocation.vue, web/src/components/steps/familyLawMatter/FlmBackground.vue, web/src/components/steps/familyLawMatter/FlmQuestionnaire.vue, web/src/components/steps/familyLawMatter/reviewFLM/PreviewFormsFLM.vue
PFCF-520: Fix Showing Form 3 instead of Form 1
=> PFCF-520: Fix Showing Form 3 instead of Form 1
